/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Diego
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        t = new javax.swing.JLabel();
        Tigre = new javax.swing.JRadioButton();
        l = new javax.swing.JLabel();
        Leon = new javax.swing.JRadioButton();
        Gato = new javax.swing.JRadioButton();
        g = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        p = new javax.swing.JLabel();
        j = new javax.swing.JLabel();
        Perro = new javax.swing.JRadioButton();
        Caballo = new javax.swing.JRadioButton();
        Jirafa = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tigre transparente.png"))); // NOI18N
        jPanel3.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 160, 180));

        buttonGroup1.add(Tigre);
        Tigre.setText("Tigre");
        jPanel3.add(Tigre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 70, -1));

        l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/leon transparente.png"))); // NOI18N
        jPanel3.add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 170, 190));

        buttonGroup1.add(Leon);
        Leon.setText("León");
        jPanel3.add(Leon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 70, -1));

        buttonGroup1.add(Gato);
        Gato.setText("Gato");
        jPanel3.add(Gato, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 80, -1));

        g.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gato transparente.png"))); // NOI18N
        jPanel3.add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 150, 180));

        c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo transparente.png"))); // NOI18N
        c.setText("a");
        jPanel3.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 150, 200));

        p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perro transparente.png"))); // NOI18N
        jPanel3.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 130, 160));

        j.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jirafa trasnparente.png"))); // NOI18N
        j.setText("jir");
        jPanel3.add(j, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 140, 170));

        buttonGroup1.add(Perro);
        Perro.setText("Perro");
        jPanel3.add(Perro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 70, -1));

        buttonGroup1.add(Caballo);
        Caballo.setText("Caballo");
        jPanel3.add(Caballo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 70, -1));

        buttonGroup1.add(Jirafa);
        Jirafa.setText("Jirafa");
        Jirafa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JirafaActionPerformed(evt);
            }
        });
        jPanel3.add(Jirafa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/selva.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 460, 350));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JirafaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JirafaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JirafaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton Caballo;
    public javax.swing.JRadioButton Gato;
    public javax.swing.JRadioButton Jirafa;
    public javax.swing.JRadioButton Leon;
    public javax.swing.JRadioButton Perro;
    public javax.swing.JRadioButton Tigre;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JLabel c;
    public javax.swing.JLabel g;
    public javax.swing.JLabel j;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JLabel l;
    public javax.swing.JLabel p;
    public javax.swing.JLabel t;
    // End of variables declaration//GEN-END:variables
}
